# Generated by Django 5.2 on 2025-04-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='on_leave',
            field=models.BooleanField(default=False),
        ),
    ]
