name: lab2

services:
  backend_service:
    container_name: backend_container
    image: backend_image
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: > 
      sh -c "
      python manage.py migrate --noinput &&
      python manage.py runserver 0.0.0.0:8000
      "
    ports:
      - "8000:8000"
    depends_on:
      postgres_service:
        condition: service_healthy

  postgres_service:
    container_name: postgres_container
    image: postgres:17-alpine
    environment:
     - POSTGRES_USER=mrifdduf
     - POSTGRES_DB=mydb
     - POSTGRES_PASSWORD=5428
    ports:
      - "1234:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=$${POSTGRES_USER} --dbname=$${POSTGRES_DB}"]  #
      interval: 1s
      timeout: 1s
      retries: 10
    volumes:
      - postgres_volume:/var/lib/postgresql/data

volumes:
  postgres_volume:    
  staticfiles_volume: