


@hostname = http://localhost:8000/


GET {{hostname}}/employee.get/1
Content-Type: application/json

###
GET {{hostname}}/employee.get
Content-Type: application/json

###update
POST {{hostname}}/employee.update/1
Content-Type: application/json

{
    "id": 1,
    "hire_date": "2023-05-10",
    "position": "Dir",
    "department": "Human Resources",
    "employee_id": "HR022",
    "is_on_leave": true
}

###delete
GET {{hostname}}/employee.delete/103
Content-Type: application/json

###create
POST {{hostname}}/employee.create
Content-Type: application/json

{
    "hire_date": "2023-05-10",
    "position": "HR Manager",
    "department": "Human Resources",
    "employee_id": "HR002",
    "is_on_leave": true
}
