# Generated by Django 5.2 on 2025-04-19 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_employee_on_leave'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='on_leave',
        ),
    ]
