@hostname = http://localhost:8080
@contentType = application/json

### Получить всех сотрудников
GET {{hostname}}/api/employees/
Content-Type: {{contentType}}

### Получить конкретного сотрудника
GET {{hostname}}/api/employees/1/
Content-Type: {{contentType}}

### Создать нового сотрудника
POST {{hostname}}/api/employees/
Content-Type: {{contentType}}

{
    "hire_date": "2023-05-10",
    "position": "HR Manager",
    "department": "Human Resources",
    "employee_id": "HR02",
    "is_on_leave": true
}

### Полное обновление сотрудника 
PUT {{hostname}}/api/employees/1/
Content-Type: {{contentType}}

{
    "hire_date": "2023-05-10",
    "position": "Director",
    "department": "Human Resources",
    "employee_id": "HR022",
    "is_on_leave": false
}

### Частичное обновление сотрудника 
PATCH {{hostname}}/api/employees/1/
Content-Type: {{contentType}}

{
    "position": "Senior Director",
    "is_on_leave": true
}

### Удалить сотрудника
DELETE {{hostname}}/api/employees/1/
Content-Type: {{contentType}}